/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import estabelecimento.Estabelecimento;
/**
 *
 * @author Pedro Rossi
 */


public class RestauranteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RestauranteFrame.class.getName());

    /**
     * Creates new form RestauranteFrame
     */
    
    private Estabelecimento estabelecimento;
    
    public RestauranteFrame() {
        initComponents();
        
        estabelecimento = new Estabelecimento("Lancheria do ZÉ");
    }

    public RestauranteFrame(Estabelecimento estabelecimento) {
    initComponents();
    this.estabelecimento = estabelecimento; 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonClienteFrame = new javax.swing.JButton();
        buttonEstabelecimentoFrame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonClienteFrame.setText("Cliente");
        buttonClienteFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClienteFrameActionPerformed(evt);
            }
        });

        buttonEstabelecimentoFrame.setText("Estabelecimento");
        buttonEstabelecimentoFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEstabelecimentoFrameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonEstabelecimentoFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClienteFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(buttonClienteFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonEstabelecimentoFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClienteFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClienteFrameActionPerformed
        ClienteNomeFrame clienteNomeFrame = new ClienteNomeFrame(estabelecimento);
        clienteNomeFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonClienteFrameActionPerformed

    private void buttonEstabelecimentoFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEstabelecimentoFrameActionPerformed
        new EstabelecimentoFrame(estabelecimento).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonEstabelecimentoFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClienteFrame;
    private javax.swing.JButton buttonEstabelecimentoFrame;
    // End of variables declaration//GEN-END:variables
}
